AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members


  PostHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.yajac.event.lambda.EventCacheHandler
      Runtime: java8
      Tags:
        project: event
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]